[connections.snowflake]
account = "EYBLCRF.AU30102"
user = "BOTYOLO"
password = 'XanILearn@123'
role = "SYSADMIN"
warehouse = "COMPUTE_DW"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
